services:
  tcc-taketicket-client:
    build: ./../projects/tcc-taketicket-client
    image: tcc-taketicket-client-image
    container_name: tcc-taketicket-client-container
    volumes:
      - ../projects/tcc-taketicket-client:/app
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  database-mongodb: 
    image: mongo
    container_name: 'database-mongodb-container'
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_USERNAME=tcc
      - MONGO_INITDB_PASSWORD=tcc
    volumes:
      - ./database/mongo:/data/db
