services:
  tcc-taketicket-client:
    build: ./../projects/tcc-taketicket-client
    image: tcc-taketicket-client-image
    container_name: tcc-taketicket-client-container
    volumes:
      - ../projects/tcc-taketicket-client:/app
    env_file:
     - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    stdin_open: true
    tty: true
  taketicket-api:
    build: ./../projects/taketicket-api
    image: taketicket-api-image
    container_name: taketicket-api-container
    volumes:
      - ../projects/taketicket-api:/app
      - '/app/node_modules'
    env_file:
     - .env
    depends_on:
      - database-mongodb
    ports:
      - ${API_PORT}:${API_PORT}
  database-mongodb: 
    image: mongo
    container_name: 'database-mongodb-container'
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./database/mongo:/data/db
